# Site Settings
title: Loek van der Beele
description: I craft digital experiences that blend beautiful design with powerful functionality.
url: "https://thunderstrike12.github.io"
baseurl: ""

# Your Info
author:
  name: Loek van der Beele
  email: loekvanderbeele@email.com
  tagline: 
  bio: "Game Programmer at BUas Y3"
  image: "/assets/images/profile.jpg"
  about: "I am a passionate game programmer, currently studying in my third year at Breda University of Applied Sciences. I have experience programming in custom engines and in Unreal Engine using C++ and I love creating systems regarding AI and physics. In my free time I play the drums, piano and various games, ranging from competitive games to 2D platformers. I also don't mind going out for a drink with friends. I am always looking for new opportunities to learn and grow as a programmer, and I am excited to see where my career takes me in the future."

# Social Links
social:
  github: https://github.com/thunderstrike12
  linkedin: https://www.linkedin.com/in/loek-van-der-beele-12b634340/
  email: mailto:loekvanderbeele@email.com

# Skills (shown in hero section)
skills:
  - icon: palette
    label: Gameplay Programming
    description: React, Node, Python
  - icon: code
    label: AI Programming
    description: Figma, Motion
  - icon: zap
    label: Physics Programming
    description: Optimization Expert

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Build Settings
markdown: kramdown
sass:
  style: compressed

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

force_polling: true